### ISSUE TITLE
ReferenceError: File is not defined

### ISSUE THREAD

**Issue by dankomax** [KABBOUCHI/laravel-mix-vue3#13]
I'm getting this error on running `npm run dev` on Windows system:

[webpack-cli] ReferenceError: File is not defined
    at C:\Users\MAX\rest_api\node_modules\laravel-mix-vue3\index.js:63:44
    at Array.map (<anonymous>)
    at Vue3.register (C:\Users\MAX\rest_api\node_modules\laravel-mix-vue3\index.js:63:30)
    at Object.components.<computed> [as vue3] (C:\Users\MAX\rest_api\node_modules\laravel-mix\src\components\ComponentRegistrar.js:133:53)
    at Object.<anonymous> (C:\Users\MAX\rest_api\webpack.mix.js:17:5)
    at Module._compile (C:\Users\MAX\rest_api\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)

**Comment by dankomax** [comment]
I found your answer on this issue already:
https://github.com/KABBOUCHI/laravel-mix-vue3/issues/11#issuecomment-760878854
